Create geekaditi-rat-in-a-maze-CPP.cpp
SidJain1412/CompetitiveProgramming pull request #48
Opened 2020-10-09 14:54 UTC by geekaditi

Solution to the Rat in a maze problem in CPP (Recursion)

2020-10-10 17:41 UTC, vishal-burman requested changes

2020-10-10 17:41 UTC, vishal-burman commented on geekaditi-rat-in-a-maze-CPP.cpp
> +    };
Hi @geekaditi Could you change the input from a hard-coded one to a generic input. The above hard-coded input can be put as a comment to show a particular example?

2020-10-10 18:40 UTC, vishal-burman commented
Hi @geekaditi you can change the filename from **geekaditi-rat-in-a-maze-CPP.cpp**  to **rat-in-a-maze.cpp**.

2020-10-10 19:40 UTC, geekaditi commented
> Hi @geekaditi you can change the filename from **geekaditi-rat-in-a-maze-CPP.cpp** to **rat-in-a-maze.cpp**.

I made the required changes. Please check now.

2020-10-10 20:13 UTC, vishal-burman commented
@geekaditi The code is returning a segmentation fault. Do a cross-check.

2020-10-10 20:38 UTC, vishal-burman requested changes

2020-10-10 20:38 UTC, vishal-burman commented on rat-in-a-maze-CPP.cpp
> +    int sol[100000][100000]={0};
```suggestion
char maze[100][100];
int sol[100][100]={0};
int main(){
```
You are overflowing the stack with a large declaration. Consider a smaller input constraint. Also declare the inputs outside of the main function if you choose larger constraints.

2020-10-11 07:53 UTC, SidJain1412 approved these changes

2020-10-11 07:54 UTC, merged

2020-10-11 07:54 UTC, SidJain1412 commented
@all-contributors please add @geekaditi for code

2020-10-11 08:04 UTC, shreayan98c commented
Please add this program to the Recursion directory.

2020-10-11 09:02 UTC, vishal-burman commented
@SidJain1412 Actually I suggested those changes and other parts of the program had to be modified because of those changes. The program is still not running. @geekaditi might need to debug the program based on those changes.

2020-10-11 09:58 UTC, vishal-burman commented
@SidJain1412 I had some free time. I have fixed the program and added some modifications in #71

2020-10-15 13:55 UTC, SidJain1412 commented
Thanks @vishal-burman @shreayan98c , my bad

2020-10-16 16:17 UTC, SidJain1412 commented
@all-contributors please add @shreayan98c for review